// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pujggdmnvscokspubzoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1amdnZG1udnNjb2tzcHViem9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NzU4NjAsImV4cCI6MjA1NTM1MTg2MH0.xc5A7CA_Y4JzbxVrsx6NivsaGIDeOVhTquekR4rbxlo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);